 import {MigrationInterface, QueryRunner} from "typeorm";

export class randomJunk1652480594091 implements MigrationInterface {
    name = 'randomJunk1652480594091'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`kmcharheading\` DROP FOREIGN KEY \`FK_6d6529e0f018e8077b948b71855\``);
        await queryRunner.query(`ALTER TABLE \`unknownimages\` DROP FOREIGN KEY \`FK_3ff4cea7cc515855a9af4c23603\``);
        await queryRunner.query(`ALTER TABLE \`unknowncomments\` DROP FOREIGN KEY \`FK_8162be53efce4b7c096b4ec4c92\``);
        await queryRunner.query(`ALTER TABLE \`omcollectionstats\` DROP FOREIGN KEY \`FK_e1c01a24d56ff7bb441160aa44e\``);
        await queryRunner.query(`ALTER TABLE \`omoccurassociations\` DROP FOREIGN KEY \`FK_8d8b1b85fbf63e150342c7415e9\``);
        await queryRunner.query(`ALTER TABLE \`omoccurdeterminations\` DROP FOREIGN KEY \`FK_06929c7d3af387ee1ba3d6816e9\``);
        await queryRunner.query(`ALTER TABLE \`fmchklsttaxalink\` DROP FOREIGN KEY \`FK_03efc6704f5b10adfa43be4b0e1\``);
        await queryRunner.query(`ALTER TABLE \`fmchklsttaxalink\` DROP FOREIGN KEY \`FK_39e01651477f19f456ba917ed48\``);
        await queryRunner.query(`ALTER TABLE \`fmchklstprojlink\` DROP FOREIGN KEY \`FK_843823fa6b0396a9e3fc65ddc53\``);
        await queryRunner.query(`ALTER TABLE \`fmchklstprojlink\` DROP FOREIGN KEY \`FK_8981f53b45317312792d7e371ca\``);
        await queryRunner.query(`ALTER TABLE \`fmchecklists\` DROP FOREIGN KEY \`FK_786b80621ec256b634bdce0acdd\``);
        await queryRunner.query(`ALTER TABLE \`fmdyncltaxalink\` DROP FOREIGN KEY \`FK_2b23ef50adfc6a1e46c147f481b\``);
        await queryRunner.query(`ALTER TABLE \`fmdyncltaxalink\` DROP FOREIGN KEY \`FK_989d2cb316fad90f8873d6a4bea\``);
        await queryRunner.query(`ALTER TABLE \`referenceobject\` DROP FOREIGN KEY \`FK_c56c972cf0c53839e150afdb93d\``);
        await queryRunner.query(`ALTER TABLE \`taxamaps\` DROP FOREIGN KEY \`FK_2a225756f69d26cd68230afa922\``);
        await queryRunner.query(`ALTER TABLE \`taxadescrblock\` DROP FOREIGN KEY \`FK_48f3943b039f61b44caa43922f4\``);
        await queryRunner.query(`ALTER TABLE \`specprocnlpversion\` DROP FOREIGN KEY \`FK_271fad29282abb098122901faa7\``);
        await queryRunner.query(`ALTER TABLE \`specprocessorrawlabels\` DROP FOREIGN KEY \`FK_96603542969ead0bd6a84928bc1\``);
        await queryRunner.query(`ALTER TABLE \`imageannotations\` DROP FOREIGN KEY \`FK_63d4db92bf943af9aac3aada88f\``);
        await queryRunner.query(`ALTER TABLE \`imageannotations\` DROP FOREIGN KEY \`FK_812ca5f8dc8bc60f363a9bad3cb\``);
        await queryRunner.query(`ALTER TABLE \`images\` DROP FOREIGN KEY \`FK_1d4c63ce117cb5ac87ee4837a39\``);
        await queryRunner.query(`ALTER TABLE \`images\` DROP FOREIGN KEY \`FK_7fcef1205b8a3883e555dbc8ca4\``);
        await queryRunner.query(`ALTER TABLE \`tmstates\` DROP FOREIGN KEY \`FK_fc976d9693dc6c435b3a6a62f50\``);
        await queryRunner.query(`ALTER TABLE \`media\` DROP FOREIGN KEY \`FK_21d40fc8c52137ce602f2227e23\``);
        await queryRunner.query(`ALTER TABLE \`omexsiccatiocclink\` DROP FOREIGN KEY \`FK_865c4fdec290c3c42f4a41773e4\``);
        await queryRunner.query(`ALTER TABLE \`omexsiccatiocclink\` DROP FOREIGN KEY \`FK_8d21497f2becd03ff82e4ddd57c\``);
        await queryRunner.query(`ALTER TABLE \`omexsiccatinumbers\` DROP FOREIGN KEY \`FK_ee76b1a41d5f9771f2c9a200e15\``);
        await queryRunner.query(`ALTER TABLE \`omcrowdsourcecentral\` DROP FOREIGN KEY \`FK_d8bfa60906d704a3c857eaca8d4\``);
        await queryRunner.query(`ALTER TABLE \`omoccurrences\` DROP FOREIGN KEY \`FK_e13f0bfb787867349925496bedc\``);
        await queryRunner.query(`ALTER TABLE \`omoccurloans\` DROP FOREIGN KEY \`FK_243aa0379ae76a14b597fd1c32c\``);
        await queryRunner.query(`ALTER TABLE \`omoccurloans\` DROP FOREIGN KEY \`FK_384ab13b97cd453624c41d7fffa\``);
        await queryRunner.query(`ALTER TABLE \`omoccurloans\` DROP FOREIGN KEY \`FK_da93ade703e97289800abfa8a64\``);
        await queryRunner.query(`ALTER TABLE \`omoccurloans\` DROP FOREIGN KEY \`FK_e595955ba9ea08e2adc05946e5e\``);
        await queryRunner.query(`ALTER TABLE \`taxstatus\` DROP FOREIGN KEY \`FK_4942cd8f6fe90a56cb413911cb5\``);
        await queryRunner.query(`ALTER TABLE \`taxstatus\` DROP FOREIGN KEY \`FK_6d480a9af6234e220d0d4b8747f\``);
        await queryRunner.query(`ALTER TABLE \`taxstatus\` DROP FOREIGN KEY \`FK_6f1ae4cbe35cef9849cce05ed13\``);
        await queryRunner.query(`ALTER TABLE \`taxstatus\` DROP FOREIGN KEY \`FK_f77ec9c9d06c35f3b7d148ad662\``);
        await queryRunner.query(`ALTER TABLE \`useraccesstokens\` DROP FOREIGN KEY \`FK_b59b4aa8c190f8d858a3afaafa1\``);
        await queryRunner.query(`ALTER TABLE \`unknowns\` DROP FOREIGN KEY \`FK_a6db886634c3a62d457c0570e8d\``);
        await queryRunner.query(`ALTER TABLE \`taxavernaculars\` DROP FOREIGN KEY \`FK_533ac17812e151d380020dab855\``);
        await queryRunner.query(`ALTER TABLE \`glossarysources\` DROP FOREIGN KEY \`FK_8d5326ea568f6b73bece53781d6\``);
        await queryRunner.query(`ALTER TABLE \`chotomouskey\` DROP FOREIGN KEY \`FK_57df0f92c80271c9d477558b6d1\``);
        await queryRunner.query(`ALTER TABLE \`taxalinks\` DROP FOREIGN KEY \`FK_18ee5f08eebb8ae9e5dbd1401fe\``);
        await queryRunner.query(`ALTER TABLE \`taxa\` DROP FOREIGN KEY \`FK_e309b68e5213aaa390e0772f22d\``);
        await queryRunner.query(`ALTER TABLE \`kmcharacters\` DROP FOREIGN KEY \`FK_9d7055dc06a75e1580db508147b\``);
        await queryRunner.query(`ALTER TABLE \`geothesmunicipality\` DROP FOREIGN KEY \`FK_0e467ab90f60e1735dd7340cc7a\``);
        await queryRunner.query(`ALTER TABLE \`geothesmunicipality\` DROP FOREIGN KEY \`FK_554f805954bd7cdacbc667ffe9c\``);
        await queryRunner.query(`ALTER TABLE \`geothescounty\` DROP FOREIGN KEY \`FK_0a5f37543f00eb4fa849db4fda4\``);
        await queryRunner.query(`ALTER TABLE \`geothescounty\` DROP FOREIGN KEY \`FK_706f087bebcdbcefe4204878911\``);
        await queryRunner.query(`ALTER TABLE \`geothesstateprovince\` DROP FOREIGN KEY \`FK_6e6d7b98acf2eaffe7a3f78ed2a\``);
        await queryRunner.query(`ALTER TABLE \`geothesstateprovince\` DROP FOREIGN KEY \`FK_c8b038a95e6f5bb739b05194f7a\``);
        await queryRunner.query(`ALTER TABLE \`geothescountry\` DROP FOREIGN KEY \`FK_04bbc928514265787ce54508af1\``);
        await queryRunner.query(`ALTER TABLE \`geothescountry\` DROP FOREIGN KEY \`FK_d601c68aa5e7c05af09b5e83c84\``);
        await queryRunner.query(`ALTER TABLE \`geothescontinent\` DROP FOREIGN KEY \`FK_db194c0b1a73b5b1ed1de5cd675\``);
        await queryRunner.query(`ALTER TABLE \`omoccurrences\` DROP COLUMN \`scientificNameAuthorship\``);
        await queryRunner.query(`CREATE INDEX \`IDX_8079fe3140daf1e7381ada9c15\` ON \`taxonunits\` (\`rankid\`)`);
        await queryRunner.query(`ALTER TABLE \`kmcharheading\` ADD CONSTRAINT \`FK_6d6529e0f018e8077b948b71855\` FOREIGN KEY (\`langid\`) REFERENCES \`adminlanguages\`(\`langid\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`unknownimages\` ADD CONSTRAINT \`FK_3ff4cea7cc515855a9af4c23603\` FOREIGN KEY (\`unkid\`) REFERENCES \`unknowns\`(\`unkid\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`unknowncomments\` ADD CONSTRAINT \`FK_8162be53efce4b7c096b4ec4c92\` FOREIGN KEY (\`unkid\`) REFERENCES \`unknowns\`(\`unkid\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`omcollectionstats\` ADD CONSTRAINT \`FK_e1c01a24d56ff7bb441160aa44e\` FOREIGN KEY (\`collid\`) REFERENCES \`omcollections\`(\`CollID\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`omoccurassociations\` ADD CONSTRAINT \`FK_8d8b1b85fbf63e150342c7415e9\` FOREIGN KEY (\`tid\`) REFERENCES \`taxa\`(\`TID\`) ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`omoccurdeterminations\` ADD CONSTRAINT \`FK_06929c7d3af387ee1ba3d6816e9\` FOREIGN KEY (\`tidinterpreted\`) REFERENCES \`taxa\`(\`TID\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`fmchklsttaxalink\` ADD CONSTRAINT \`FK_39e01651477f19f456ba917ed48\` FOREIGN KEY (\`CLID\`) REFERENCES \`fmchecklists\`(\`CLID\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`fmchklsttaxalink\` ADD CONSTRAINT \`FK_03efc6704f5b10adfa43be4b0e1\` FOREIGN KEY (\`TID\`) REFERENCES \`taxa\`(\`TID\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`fmchklstprojlink\` ADD CONSTRAINT \`FK_843823fa6b0396a9e3fc65ddc53\` FOREIGN KEY (\`clid\`) REFERENCES \`fmchecklists\`(\`CLID\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`fmchklstprojlink\` ADD CONSTRAINT \`FK_8981f53b45317312792d7e371ca\` FOREIGN KEY (\`pid\`) REFERENCES \`fmprojects\`(\`pid\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`fmchecklists\` ADD CONSTRAINT \`FK_786b80621ec256b634bdce0acdd\` FOREIGN KEY (\`uid\`) REFERENCES \`users\`(\`uid\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`fmdyncltaxalink\` ADD CONSTRAINT \`FK_2b23ef50adfc6a1e46c147f481b\` FOREIGN KEY (\`dynclid\`) REFERENCES \`fmdynamicchecklists\`(\`dynclid\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`fmdyncltaxalink\` ADD CONSTRAINT \`FK_989d2cb316fad90f8873d6a4bea\` FOREIGN KEY (\`tid\`) REFERENCES \`taxa\`(\`TID\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`referenceobject\` ADD CONSTRAINT \`FK_c56c972cf0c53839e150afdb93d\` FOREIGN KEY (\`ReferenceTypeId\`) REFERENCES \`referencetype\`(\`ReferenceTypeId\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`taxamaps\` ADD CONSTRAINT \`FK_2a225756f69d26cd68230afa922\` FOREIGN KEY (\`tid\`) REFERENCES \`taxa\`(\`TID\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`taxadescrblock\` ADD CONSTRAINT \`FK_48f3943b039f61b44caa43922f4\` FOREIGN KEY (\`tid\`) REFERENCES \`taxa\`(\`TID\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`specprocnlpversion\` ADD CONSTRAINT \`FK_271fad29282abb098122901faa7\` FOREIGN KEY (\`prlid\`) REFERENCES \`specprocessorrawlabels\`(\`prlid\`) ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`specprocessorrawlabels\` ADD CONSTRAINT \`FK_96603542969ead0bd6a84928bc1\` FOREIGN KEY (\`imgid\`) REFERENCES \`images\`(\`imgid\`) ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`imageannotations\` ADD CONSTRAINT \`FK_812ca5f8dc8bc60f363a9bad3cb\` FOREIGN KEY (\`imgid\`) REFERENCES \`images\`(\`imgid\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`imageannotations\` ADD CONSTRAINT \`FK_63d4db92bf943af9aac3aada88f\` FOREIGN KEY (\`tid\`) REFERENCES \`taxa\`(\`TID\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`images\` ADD CONSTRAINT \`FK_1d4c63ce117cb5ac87ee4837a39\` FOREIGN KEY (\`occid\`) REFERENCES \`omoccurrences\`(\`occid\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`images\` ADD CONSTRAINT \`FK_7fcef1205b8a3883e555dbc8ca4\` FOREIGN KEY (\`tid\`) REFERENCES \`taxa\`(\`TID\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`tmstates\` ADD CONSTRAINT \`FK_fc976d9693dc6c435b3a6a62f50\` FOREIGN KEY (\`traitid\`) REFERENCES \`tmtraits\`(\`traitid\`) ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`media\` ADD CONSTRAINT \`FK_21d40fc8c52137ce602f2227e23\` FOREIGN KEY (\`tid\`) REFERENCES \`taxa\`(\`TID\`) ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`omexsiccatiocclink\` ADD CONSTRAINT \`FK_8d21497f2becd03ff82e4ddd57c\` FOREIGN KEY (\`omenid\`) REFERENCES \`omexsiccatinumbers\`(\`omenid\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`omexsiccatiocclink\` ADD CONSTRAINT \`FK_865c4fdec290c3c42f4a41773e4\` FOREIGN KEY (\`occid\`) REFERENCES \`omoccurrences\`(\`occid\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`omexsiccatinumbers\` ADD CONSTRAINT \`FK_ee76b1a41d5f9771f2c9a200e15\` FOREIGN KEY (\`ometid\`) REFERENCES \`omexsiccatititles\`(\`ometid\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`omcrowdsourcecentral\` ADD CONSTRAINT \`FK_d8bfa60906d704a3c857eaca8d4\` FOREIGN KEY (\`collid\`) REFERENCES \`omcollections\`(\`CollID\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`omoccurrences\` ADD CONSTRAINT \`FK_e13f0bfb787867349925496bedc\` FOREIGN KEY (\`observeruid\`) REFERENCES \`users\`(\`uid\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`omoccurloans\` ADD CONSTRAINT \`FK_da93ade703e97289800abfa8a64\` FOREIGN KEY (\`collidBorr\`) REFERENCES \`omcollections\`(\`CollID\`) ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`omoccurloans\` ADD CONSTRAINT \`FK_e595955ba9ea08e2adc05946e5e\` FOREIGN KEY (\`iidBorrower\`) REFERENCES \`institutions\`(\`iid\`) ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`omoccurloans\` ADD CONSTRAINT \`FK_384ab13b97cd453624c41d7fffa\` FOREIGN KEY (\`collidOwn\`) REFERENCES \`omcollections\`(\`CollID\`) ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`omoccurloans\` ADD CONSTRAINT \`FK_243aa0379ae76a14b597fd1c32c\` FOREIGN KEY (\`iidOwner\`) REFERENCES \`institutions\`(\`iid\`) ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`taxstatus\` ADD CONSTRAINT \`FK_f77ec9c9d06c35f3b7d148ad662\` FOREIGN KEY (\`parenttid\`) REFERENCES \`taxa\`(\`TID\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`taxstatus\` ADD CONSTRAINT \`FK_6f1ae4cbe35cef9849cce05ed13\` FOREIGN KEY (\`taxauthid\`) REFERENCES \`taxauthority\`(\`taxauthid\`) ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`taxstatus\` ADD CONSTRAINT \`FK_4942cd8f6fe90a56cb413911cb5\` FOREIGN KEY (\`tid\`) REFERENCES \`taxa\`(\`TID\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`taxstatus\` ADD CONSTRAINT \`FK_6d480a9af6234e220d0d4b8747f\` FOREIGN KEY (\`tidaccepted\`) REFERENCES \`taxa\`(\`TID\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`useraccesstokens\` ADD CONSTRAINT \`FK_b59b4aa8c190f8d858a3afaafa1\` FOREIGN KEY (\`uid\`) REFERENCES \`users\`(\`uid\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`unknowns\` ADD CONSTRAINT \`FK_a6db886634c3a62d457c0570e8d\` FOREIGN KEY (\`tid\`) REFERENCES \`taxa\`(\`TID\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`taxavernaculars\` ADD CONSTRAINT \`FK_533ac17812e151d380020dab855\` FOREIGN KEY (\`TID\`) REFERENCES \`taxa\`(\`TID\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`glossarysources\` ADD CONSTRAINT \`FK_8d5326ea568f6b73bece53781d6\` FOREIGN KEY (\`tid\`) REFERENCES \`taxa\`(\`TID\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`chotomouskey\` ADD CONSTRAINT \`FK_57df0f92c80271c9d477558b6d1\` FOREIGN KEY (\`tid\`) REFERENCES \`taxa\`(\`TID\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`taxalinks\` ADD CONSTRAINT \`FK_18ee5f08eebb8ae9e5dbd1401fe\` FOREIGN KEY (\`tid\`) REFERENCES \`taxa\`(\`TID\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`taxa\` ADD CONSTRAINT \`FK_e309b68e5213aaa390e0772f22d\` FOREIGN KEY (\`modifiedUid\`) REFERENCES \`users\`(\`uid\`) ON DELETE NO ACTION ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`kmcharacters\` ADD CONSTRAINT \`FK_9d7055dc06a75e1580db508147b\` FOREIGN KEY (\`hid\`) REFERENCES \`kmcharheading\`(\`hid\`) ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`geothesmunicipality\` ADD CONSTRAINT \`FK_554f805954bd7cdacbc667ffe9c\` FOREIGN KEY (\`acceptedid\`) REFERENCES \`geothesmunicipality\`(\`gtmid\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`geothesmunicipality\` ADD CONSTRAINT \`FK_0e467ab90f60e1735dd7340cc7a\` FOREIGN KEY (\`countyid\`) REFERENCES \`geothescounty\`(\`gtcoid\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`geothescounty\` ADD CONSTRAINT \`FK_706f087bebcdbcefe4204878911\` FOREIGN KEY (\`acceptedid\`) REFERENCES \`geothescounty\`(\`gtcoid\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`geothescounty\` ADD CONSTRAINT \`FK_0a5f37543f00eb4fa849db4fda4\` FOREIGN KEY (\`stateid\`) REFERENCES \`geothesstateprovince\`(\`gtspid\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`geothesstateprovince\` ADD CONSTRAINT \`FK_c8b038a95e6f5bb739b05194f7a\` FOREIGN KEY (\`acceptedid\`) REFERENCES \`geothesstateprovince\`(\`gtspid\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`geothesstateprovince\` ADD CONSTRAINT \`FK_6e6d7b98acf2eaffe7a3f78ed2a\` FOREIGN KEY (\`countryid\`) REFERENCES \`geothescountry\`(\`gtcid\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`geothescountry\` ADD CONSTRAINT \`FK_d601c68aa5e7c05af09b5e83c84\` FOREIGN KEY (\`acceptedid\`) REFERENCES \`geothescountry\`(\`gtcid\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`geothescountry\` ADD CONSTRAINT \`FK_04bbc928514265787ce54508af1\` FOREIGN KEY (\`continentid\`) REFERENCES \`geothescontinent\`(\`gtcid\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`geothescontinent\` ADD CONSTRAINT \`FK_db194c0b1a73b5b1ed1de5cd675\` FOREIGN KEY (\`acceptedid\`) REFERENCES \`geothescontinent\`(\`gtcid\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`geothescontinent\` DROP FOREIGN KEY \`FK_db194c0b1a73b5b1ed1de5cd675\``);
        await queryRunner.query(`ALTER TABLE \`geothescountry\` DROP FOREIGN KEY \`FK_04bbc928514265787ce54508af1\``);
        await queryRunner.query(`ALTER TABLE \`geothescountry\` DROP FOREIGN KEY \`FK_d601c68aa5e7c05af09b5e83c84\``);
        await queryRunner.query(`ALTER TABLE \`geothesstateprovince\` DROP FOREIGN KEY \`FK_6e6d7b98acf2eaffe7a3f78ed2a\``);
        await queryRunner.query(`ALTER TABLE \`geothesstateprovince\` DROP FOREIGN KEY \`FK_c8b038a95e6f5bb739b05194f7a\``);
        await queryRunner.query(`ALTER TABLE \`geothescounty\` DROP FOREIGN KEY \`FK_0a5f37543f00eb4fa849db4fda4\``);
        await queryRunner.query(`ALTER TABLE \`geothescounty\` DROP FOREIGN KEY \`FK_706f087bebcdbcefe4204878911\``);
        await queryRunner.query(`ALTER TABLE \`geothesmunicipality\` DROP FOREIGN KEY \`FK_0e467ab90f60e1735dd7340cc7a\``);
        await queryRunner.query(`ALTER TABLE \`geothesmunicipality\` DROP FOREIGN KEY \`FK_554f805954bd7cdacbc667ffe9c\``);
        await queryRunner.query(`ALTER TABLE \`kmcharacters\` DROP FOREIGN KEY \`FK_9d7055dc06a75e1580db508147b\``);
        await queryRunner.query(`ALTER TABLE \`taxa\` DROP FOREIGN KEY \`FK_e309b68e5213aaa390e0772f22d\``);
        await queryRunner.query(`ALTER TABLE \`taxalinks\` DROP FOREIGN KEY \`FK_18ee5f08eebb8ae9e5dbd1401fe\``);
        await queryRunner.query(`ALTER TABLE \`chotomouskey\` DROP FOREIGN KEY \`FK_57df0f92c80271c9d477558b6d1\``);
        await queryRunner.query(`ALTER TABLE \`glossarysources\` DROP FOREIGN KEY \`FK_8d5326ea568f6b73bece53781d6\``);
        await queryRunner.query(`ALTER TABLE \`taxavernaculars\` DROP FOREIGN KEY \`FK_533ac17812e151d380020dab855\``);
        await queryRunner.query(`ALTER TABLE \`unknowns\` DROP FOREIGN KEY \`FK_a6db886634c3a62d457c0570e8d\``);
        await queryRunner.query(`ALTER TABLE \`useraccesstokens\` DROP FOREIGN KEY \`FK_b59b4aa8c190f8d858a3afaafa1\``);
        await queryRunner.query(`ALTER TABLE \`taxstatus\` DROP FOREIGN KEY \`FK_6d480a9af6234e220d0d4b8747f\``);
        await queryRunner.query(`ALTER TABLE \`taxstatus\` DROP FOREIGN KEY \`FK_4942cd8f6fe90a56cb413911cb5\``);
        await queryRunner.query(`ALTER TABLE \`taxstatus\` DROP FOREIGN KEY \`FK_6f1ae4cbe35cef9849cce05ed13\``);
        await queryRunner.query(`ALTER TABLE \`taxstatus\` DROP FOREIGN KEY \`FK_f77ec9c9d06c35f3b7d148ad662\``);
        await queryRunner.query(`ALTER TABLE \`omoccurloans\` DROP FOREIGN KEY \`FK_243aa0379ae76a14b597fd1c32c\``);
        await queryRunner.query(`ALTER TABLE \`omoccurloans\` DROP FOREIGN KEY \`FK_384ab13b97cd453624c41d7fffa\``);
        await queryRunner.query(`ALTER TABLE \`omoccurloans\` DROP FOREIGN KEY \`FK_e595955ba9ea08e2adc05946e5e\``);
        await queryRunner.query(`ALTER TABLE \`omoccurloans\` DROP FOREIGN KEY \`FK_da93ade703e97289800abfa8a64\``);
        await queryRunner.query(`ALTER TABLE \`omoccurrences\` DROP FOREIGN KEY \`FK_e13f0bfb787867349925496bedc\``);
        await queryRunner.query(`ALTER TABLE \`omcrowdsourcecentral\` DROP FOREIGN KEY \`FK_d8bfa60906d704a3c857eaca8d4\``);
        await queryRunner.query(`ALTER TABLE \`omexsiccatinumbers\` DROP FOREIGN KEY \`FK_ee76b1a41d5f9771f2c9a200e15\``);
        await queryRunner.query(`ALTER TABLE \`omexsiccatiocclink\` DROP FOREIGN KEY \`FK_865c4fdec290c3c42f4a41773e4\``);
        await queryRunner.query(`ALTER TABLE \`omexsiccatiocclink\` DROP FOREIGN KEY \`FK_8d21497f2becd03ff82e4ddd57c\``);
        await queryRunner.query(`ALTER TABLE \`media\` DROP FOREIGN KEY \`FK_21d40fc8c52137ce602f2227e23\``);
        await queryRunner.query(`ALTER TABLE \`tmstates\` DROP FOREIGN KEY \`FK_fc976d9693dc6c435b3a6a62f50\``);
        await queryRunner.query(`ALTER TABLE \`images\` DROP FOREIGN KEY \`FK_7fcef1205b8a3883e555dbc8ca4\``);
        await queryRunner.query(`ALTER TABLE \`images\` DROP FOREIGN KEY \`FK_1d4c63ce117cb5ac87ee4837a39\``);
        await queryRunner.query(`ALTER TABLE \`imageannotations\` DROP FOREIGN KEY \`FK_63d4db92bf943af9aac3aada88f\``);
        await queryRunner.query(`ALTER TABLE \`imageannotations\` DROP FOREIGN KEY \`FK_812ca5f8dc8bc60f363a9bad3cb\``);
        await queryRunner.query(`ALTER TABLE \`specprocessorrawlabels\` DROP FOREIGN KEY \`FK_96603542969ead0bd6a84928bc1\``);
        await queryRunner.query(`ALTER TABLE \`specprocnlpversion\` DROP FOREIGN KEY \`FK_271fad29282abb098122901faa7\``);
        await queryRunner.query(`ALTER TABLE \`taxadescrblock\` DROP FOREIGN KEY \`FK_48f3943b039f61b44caa43922f4\``);
        await queryRunner.query(`ALTER TABLE \`taxamaps\` DROP FOREIGN KEY \`FK_2a225756f69d26cd68230afa922\``);
        await queryRunner.query(`ALTER TABLE \`referenceobject\` DROP FOREIGN KEY \`FK_c56c972cf0c53839e150afdb93d\``);
        await queryRunner.query(`ALTER TABLE \`fmdyncltaxalink\` DROP FOREIGN KEY \`FK_989d2cb316fad90f8873d6a4bea\``);
        await queryRunner.query(`ALTER TABLE \`fmdyncltaxalink\` DROP FOREIGN KEY \`FK_2b23ef50adfc6a1e46c147f481b\``);
        await queryRunner.query(`ALTER TABLE \`fmchecklists\` DROP FOREIGN KEY \`FK_786b80621ec256b634bdce0acdd\``);
        await queryRunner.query(`ALTER TABLE \`fmchklstprojlink\` DROP FOREIGN KEY \`FK_8981f53b45317312792d7e371ca\``);
        await queryRunner.query(`ALTER TABLE \`fmchklstprojlink\` DROP FOREIGN KEY \`FK_843823fa6b0396a9e3fc65ddc53\``);
        await queryRunner.query(`ALTER TABLE \`fmchklsttaxalink\` DROP FOREIGN KEY \`FK_03efc6704f5b10adfa43be4b0e1\``);
        await queryRunner.query(`ALTER TABLE \`fmchklsttaxalink\` DROP FOREIGN KEY \`FK_39e01651477f19f456ba917ed48\``);
        await queryRunner.query(`ALTER TABLE \`omoccurdeterminations\` DROP FOREIGN KEY \`FK_06929c7d3af387ee1ba3d6816e9\``);
        await queryRunner.query(`ALTER TABLE \`omoccurassociations\` DROP FOREIGN KEY \`FK_8d8b1b85fbf63e150342c7415e9\``);
        await queryRunner.query(`ALTER TABLE \`omcollectionstats\` DROP FOREIGN KEY \`FK_e1c01a24d56ff7bb441160aa44e\``);
        await queryRunner.query(`ALTER TABLE \`unknowncomments\` DROP FOREIGN KEY \`FK_8162be53efce4b7c096b4ec4c92\``);
        await queryRunner.query(`ALTER TABLE \`unknownimages\` DROP FOREIGN KEY \`FK_3ff4cea7cc515855a9af4c23603\``);
        await queryRunner.query(`ALTER TABLE \`kmcharheading\` DROP FOREIGN KEY \`FK_6d6529e0f018e8077b948b71855\``);
        await queryRunner.query(`DROP INDEX \`IDX_8079fe3140daf1e7381ada9c15\` ON \`taxonunits\``);
        await queryRunner.query(`ALTER TABLE \`omoccurrences\` ADD \`scientificNameAuthorship\` varchar(255) CHARACTER SET "utf8" COLLATE "utf8_general_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`geothescontinent\` ADD CONSTRAINT \`FK_db194c0b1a73b5b1ed1de5cd675\` FOREIGN KEY (\`acceptedid\`) REFERENCES \`geothescontinent\`(\`gtcid\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`geothescountry\` ADD CONSTRAINT \`FK_d601c68aa5e7c05af09b5e83c84\` FOREIGN KEY (\`acceptedid\`) REFERENCES \`geothescountry\`(\`gtcid\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`geothescountry\` ADD CONSTRAINT \`FK_04bbc928514265787ce54508af1\` FOREIGN KEY (\`continentid\`) REFERENCES \`geothescontinent\`(\`gtcid\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`geothesstateprovince\` ADD CONSTRAINT \`FK_c8b038a95e6f5bb739b05194f7a\` FOREIGN KEY (\`acceptedid\`) REFERENCES \`geothesstateprovince\`(\`gtspid\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`geothesstateprovince\` ADD CONSTRAINT \`FK_6e6d7b98acf2eaffe7a3f78ed2a\` FOREIGN KEY (\`countryid\`) REFERENCES \`geothescountry\`(\`gtcid\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`geothescounty\` ADD CONSTRAINT \`FK_706f087bebcdbcefe4204878911\` FOREIGN KEY (\`acceptedid\`) REFERENCES \`geothescounty\`(\`gtcoid\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`geothescounty\` ADD CONSTRAINT \`FK_0a5f37543f00eb4fa849db4fda4\` FOREIGN KEY (\`stateid\`) REFERENCES \`geothesstateprovince\`(\`gtspid\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`geothesmunicipality\` ADD CONSTRAINT \`FK_554f805954bd7cdacbc667ffe9c\` FOREIGN KEY (\`acceptedid\`) REFERENCES \`geothesmunicipality\`(\`gtmid\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`geothesmunicipality\` ADD CONSTRAINT \`FK_0e467ab90f60e1735dd7340cc7a\` FOREIGN KEY (\`countyid\`) REFERENCES \`geothescounty\`(\`gtcoid\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`kmcharacters\` ADD CONSTRAINT \`FK_9d7055dc06a75e1580db508147b\` FOREIGN KEY (\`hid\`) REFERENCES \`kmcharheading\`(\`hid\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`taxa\` ADD CONSTRAINT \`FK_e309b68e5213aaa390e0772f22d\` FOREIGN KEY (\`modifiedUid\`) REFERENCES \`users\`(\`uid\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`taxalinks\` ADD CONSTRAINT \`FK_18ee5f08eebb8ae9e5dbd1401fe\` FOREIGN KEY (\`tid\`) REFERENCES \`taxa\`(\`TID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`chotomouskey\` ADD CONSTRAINT \`FK_57df0f92c80271c9d477558b6d1\` FOREIGN KEY (\`tid\`) REFERENCES \`taxa\`(\`TID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`glossarysources\` ADD CONSTRAINT \`FK_8d5326ea568f6b73bece53781d6\` FOREIGN KEY (\`tid\`) REFERENCES \`taxa\`(\`TID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`taxavernaculars\` ADD CONSTRAINT \`FK_533ac17812e151d380020dab855\` FOREIGN KEY (\`TID\`) REFERENCES \`taxa\`(\`TID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`unknowns\` ADD CONSTRAINT \`FK_a6db886634c3a62d457c0570e8d\` FOREIGN KEY (\`tid\`) REFERENCES \`taxa\`(\`TID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`useraccesstokens\` ADD CONSTRAINT \`FK_b59b4aa8c190f8d858a3afaafa1\` FOREIGN KEY (\`uid\`) REFERENCES \`users\`(\`uid\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`taxstatus\` ADD CONSTRAINT \`FK_f77ec9c9d06c35f3b7d148ad662\` FOREIGN KEY (\`parenttid\`) REFERENCES \`taxa\`(\`TID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`taxstatus\` ADD CONSTRAINT \`FK_6f1ae4cbe35cef9849cce05ed13\` FOREIGN KEY (\`taxauthid\`) REFERENCES \`taxauthority\`(\`taxauthid\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`taxstatus\` ADD CONSTRAINT \`FK_6d480a9af6234e220d0d4b8747f\` FOREIGN KEY (\`tidaccepted\`) REFERENCES \`taxa\`(\`TID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`taxstatus\` ADD CONSTRAINT \`FK_4942cd8f6fe90a56cb413911cb5\` FOREIGN KEY (\`tid\`) REFERENCES \`taxa\`(\`TID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`omoccurloans\` ADD CONSTRAINT \`FK_e595955ba9ea08e2adc05946e5e\` FOREIGN KEY (\`iidBorrower\`) REFERENCES \`institutions\`(\`iid\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`omoccurloans\` ADD CONSTRAINT \`FK_da93ade703e97289800abfa8a64\` FOREIGN KEY (\`collidBorr\`) REFERENCES \`omcollections\`(\`CollID\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`omoccurloans\` ADD CONSTRAINT \`FK_384ab13b97cd453624c41d7fffa\` FOREIGN KEY (\`collidOwn\`) REFERENCES \`omcollections\`(\`CollID\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`omoccurloans\` ADD CONSTRAINT \`FK_243aa0379ae76a14b597fd1c32c\` FOREIGN KEY (\`iidOwner\`) REFERENCES \`institutions\`(\`iid\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`omoccurrences\` ADD CONSTRAINT \`FK_e13f0bfb787867349925496bedc\` FOREIGN KEY (\`observeruid\`) REFERENCES \`users\`(\`uid\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`omcrowdsourcecentral\` ADD CONSTRAINT \`FK_d8bfa60906d704a3c857eaca8d4\` FOREIGN KEY (\`collid\`) REFERENCES \`omcollections\`(\`CollID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`omexsiccatinumbers\` ADD CONSTRAINT \`FK_ee76b1a41d5f9771f2c9a200e15\` FOREIGN KEY (\`ometid\`) REFERENCES \`omexsiccatititles\`(\`ometid\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`omexsiccatiocclink\` ADD CONSTRAINT \`FK_8d21497f2becd03ff82e4ddd57c\` FOREIGN KEY (\`omenid\`) REFERENCES \`omexsiccatinumbers\`(\`omenid\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`omexsiccatiocclink\` ADD CONSTRAINT \`FK_865c4fdec290c3c42f4a41773e4\` FOREIGN KEY (\`occid\`) REFERENCES \`omoccurrences\`(\`occid\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`media\` ADD CONSTRAINT \`FK_21d40fc8c52137ce602f2227e23\` FOREIGN KEY (\`tid\`) REFERENCES \`taxa\`(\`TID\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`tmstates\` ADD CONSTRAINT \`FK_fc976d9693dc6c435b3a6a62f50\` FOREIGN KEY (\`traitid\`) REFERENCES \`tmtraits\`(\`traitid\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`images\` ADD CONSTRAINT \`FK_7fcef1205b8a3883e555dbc8ca4\` FOREIGN KEY (\`tid\`) REFERENCES \`taxa\`(\`TID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`images\` ADD CONSTRAINT \`FK_1d4c63ce117cb5ac87ee4837a39\` FOREIGN KEY (\`occid\`) REFERENCES \`omoccurrences\`(\`occid\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`imageannotations\` ADD CONSTRAINT \`FK_812ca5f8dc8bc60f363a9bad3cb\` FOREIGN KEY (\`imgid\`) REFERENCES \`images\`(\`imgid\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`imageannotations\` ADD CONSTRAINT \`FK_63d4db92bf943af9aac3aada88f\` FOREIGN KEY (\`tid\`) REFERENCES \`taxa\`(\`TID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`specprocessorrawlabels\` ADD CONSTRAINT \`FK_96603542969ead0bd6a84928bc1\` FOREIGN KEY (\`imgid\`) REFERENCES \`images\`(\`imgid\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`specprocnlpversion\` ADD CONSTRAINT \`FK_271fad29282abb098122901faa7\` FOREIGN KEY (\`prlid\`) REFERENCES \`specprocessorrawlabels\`(\`prlid\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`taxadescrblock\` ADD CONSTRAINT \`FK_48f3943b039f61b44caa43922f4\` FOREIGN KEY (\`tid\`) REFERENCES \`taxa\`(\`TID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`taxamaps\` ADD CONSTRAINT \`FK_2a225756f69d26cd68230afa922\` FOREIGN KEY (\`tid\`) REFERENCES \`taxa\`(\`TID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`referenceobject\` ADD CONSTRAINT \`FK_c56c972cf0c53839e150afdb93d\` FOREIGN KEY (\`ReferenceTypeId\`) REFERENCES \`referencetype\`(\`ReferenceTypeId\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fmdyncltaxalink\` ADD CONSTRAINT \`FK_989d2cb316fad90f8873d6a4bea\` FOREIGN KEY (\`tid\`) REFERENCES \`taxa\`(\`TID\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fmdyncltaxalink\` ADD CONSTRAINT \`FK_2b23ef50adfc6a1e46c147f481b\` FOREIGN KEY (\`dynclid\`) REFERENCES \`fmdynamicchecklists\`(\`dynclid\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fmchecklists\` ADD CONSTRAINT \`FK_786b80621ec256b634bdce0acdd\` FOREIGN KEY (\`uid\`) REFERENCES \`users\`(\`uid\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fmchklstprojlink\` ADD CONSTRAINT \`FK_8981f53b45317312792d7e371ca\` FOREIGN KEY (\`pid\`) REFERENCES \`fmprojects\`(\`pid\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fmchklstprojlink\` ADD CONSTRAINT \`FK_843823fa6b0396a9e3fc65ddc53\` FOREIGN KEY (\`clid\`) REFERENCES \`fmchecklists\`(\`CLID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fmchklsttaxalink\` ADD CONSTRAINT \`FK_39e01651477f19f456ba917ed48\` FOREIGN KEY (\`CLID\`) REFERENCES \`fmchecklists\`(\`CLID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fmchklsttaxalink\` ADD CONSTRAINT \`FK_03efc6704f5b10adfa43be4b0e1\` FOREIGN KEY (\`TID\`) REFERENCES \`taxa\`(\`TID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`omoccurdeterminations\` ADD CONSTRAINT \`FK_06929c7d3af387ee1ba3d6816e9\` FOREIGN KEY (\`tidinterpreted\`) REFERENCES \`taxa\`(\`TID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`omoccurassociations\` ADD CONSTRAINT \`FK_8d8b1b85fbf63e150342c7415e9\` FOREIGN KEY (\`tid\`) REFERENCES \`taxa\`(\`TID\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`omcollectionstats\` ADD CONSTRAINT \`FK_e1c01a24d56ff7bb441160aa44e\` FOREIGN KEY (\`collid\`) REFERENCES \`omcollections\`(\`CollID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`unknowncomments\` ADD CONSTRAINT \`FK_8162be53efce4b7c096b4ec4c92\` FOREIGN KEY (\`unkid\`) REFERENCES \`unknowns\`(\`unkid\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`unknownimages\` ADD CONSTRAINT \`FK_3ff4cea7cc515855a9af4c23603\` FOREIGN KEY (\`unkid\`) REFERENCES \`unknowns\`(\`unkid\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`kmcharheading\` ADD CONSTRAINT \`FK_6d6529e0f018e8077b948b71855\` FOREIGN KEY (\`langid\`) REFERENCES \`adminlanguages\`(\`langid\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
