stages:
    - test
    - deploy

"Build & run tests":
    image: "node:14"
    stage: test
    coverage: /All\sfiles.*?\s+(\d+.\d+)/
    script:
        - npm i
        - npm run build
#        - npm run test:cov

"Deploy to demo.symbiota2.org":
    image: "alpine:latest"
    stage: deploy
    before_script:
        - apk add openssh-client
        - mkdir -m 700 ~/.ssh
        - cp "$SYMBIOTA2_AWS_SSH" ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519
        - printf 'Host *\n' > ~/.ssh/config
        - printf '\tStrictHostKeyChecking no\n' >> ~/.ssh/config
        - printf '\tUser symbiota2\n' >> ~/.ssh/config
        - printf '\tIdentityFile ~/.ssh/id_ed25519\n' >> ~/.ssh/config
    script:
        - ssh demo.symbiota2.org 'cd app && git reset --hard HEAD && git pull'
        - "scp $PROD_UI_ENVIRON demo.symbiota2.org:app/apps/ui/src/environments/environment.prod.ts"
        - ssh demo.symbiota2.org 'sudo systemctl restart symbiota2'

    # Don't build on tags or merge requests, and only on the master branch
    rules:
        - if: $CI_COMMIT_TAG
          when: never
        - if: $CI_MERGE_REQUEST_ID
          when: never
        - if: '$CI_COMMIT_BRANCH == "master"'
          when: on_success
