
services:
  mariadb:
    image: "mariadb:10.5"
    container_name: s2-mariadb
    environment:
      TZ: "America/Phoenix"
      MYSQL_ROOT_PASSWORD: ${SYMBIOTA2_DATABASE_PASSWORD:-password}
    # To allow for big BLOB values; default is 64M
    command: ["--max_allowed_packet=256M"]
    volumes:
      - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
      - "${SYMBIOTA2_DATABASE_VOLUME:-s2-db:/var/lib/mysql}"
    ports: ["${SYMBIOTA2_DATABASE_PORT:-3306}:3306"]

  redis:
    image: "redis:6"
    container_name: s2-redis
    command: "redis-server --appendonly yes"
    volumes: ["redis:/data"]
    ports: ["${SYMBIOTA2_REDIS_PORT:-6379}:6379"]

  s3:
    image: "quay.io/minio/minio:RELEASE.2021-09-24T00-24-24Z"
    container_name: s2-storage
    environment:
      MINIO_ROOT_USER: ${SYMBIOTA2_MINIO_ROOT_USER:-symbiota2}
      MINIO_ROOT_PASSWORD: ${SYMBIOTA2_MINIO_ROOT_PASSWORD:-password}
    command: "server /data --console-address ':9001'"
    volumes: ["s3:/data"]
    ports:
      - "${SYMBIOTA2_S3_HOST:-127.0.0.1}:${SYMBIOTA2_S3_PORT1:-9000}:9000"
      - "${SYMBIOTA2_S3_HOST:-127.0.0.1}:${SYMBIOTA2_S3_PORT2:-9001}:9001"

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      - PMA_HOST: mariadb
      - PMA_PASSWORD: ${SYMBIOTA2_DATABASE_PASSWORD:-password}
    restart: unless-stopped

volumes:
  s2-db: { name: s2-db }
  redis: { name: s2-redis }
  s3: { name: s2-storage }


