
services:
  mariadb:
    image: "mariadb:10.5"
    container_name: s2-mariadb
    environment:
      TZ: "America/Phoenix"
      MYSQL_ROOT_PASSWORD: password
    # To allow for big BLOB values; default is 64M
    command: ["--max_allowed_packet=256M"]
    volumes:
      - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
      - "s2-db:/var/lib/mysql"
    ports: ["3306:3306"]

  redis:
    image: "redis:6"
    container_name: s2-redis
    command: "redis-server --appendonly yes"
    volumes: ["redis:/data"]
    ports: ["6379:6379"]

volumes:
  s2-db: { name: s2-db }
  redis: { name: s2-redis }
