module.exports = {
  projects: [
    '<rootDir>/apps/api',
    '<rootDir>/apps/ui',
    '<rootDir>/libs/ui-common',
    '<rootDir>/libs/ui-plugin-occurrence',
    '<rootDir>/libs/ui-plugin-collection',
    '<rootDir>/libs/ui-plugin-taxonomy',
    '<rootDir>/libs/ui-plugin-image',
    '<rootDir>/libs/api-common',
    '<rootDir>/libs/api-config',
    '<rootDir>/libs/api-database',
    '<rootDir>/libs/api-auth',
    '<rootDir>/libs/api-plugin-collection',
    '<rootDir>/libs/api-plugin-occurrence',
    '<rootDir>/libs/api-plugin-image',
    '<rootDir>/libs/api-plugin-taxonomy',
    '<rootDir>/libs/data-access',
    '<rootDir>/libs/api-plugin-geography',
    '<rootDir>/libs/ui-plugin-geography',
    '<rootDir>/libs/dwc',
    '<rootDir>/libs/api-email',
    '<rootDir>/libs/api-storage',
  ],
};
