// Add the index.ts for each module in src
export * from './taxon/public-api'
export * from './taxonomicAuthority/public-api'
export * from './taxonomicStatus/public-api'
export * from './taxonomicEnumTree/public-api'
export * from './taxonVernacular/public-api'
export * from './taxonDescriptionBlock/public-api'
export * from './taxonDescriptionStatement/public-api'
export * from './taxonResourceLink/public-api'
export * from './taxonLink/public-api'
export * from './taxonProfilePublication/public-api'
export * from './taxonProfilePublicationImageLink/public-api'
export * from './taxonProfilePublicationDescriptionLink/public-api'
